import type { Category, Product, Flyer } from "@/types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Vegetables",
    slug: "vegetables",
    image: "/fresh-vegetables-market.jpg",
    subcategories: [
      {
        id: "1-1",
        name: "Leafy Greens",
        slug: "leafy-greens",
        subSubcategories: [
          { id: "1-1-1", name: "Spinach", slug: "spinach" },
          { id: "1-1-2", name: "Lettuce", slug: "lettuce" },
          { id: "1-1-3", name: "Kale", slug: "kale" },
        ],
      },
      {
        id: "1-2",
        name: "Root Vegetables",
        slug: "root-vegetables",
        subSubcategories: [
          { id: "1-2-1", name: "Carrots", slug: "carrots" },
          { id: "1-2-2", name: "Potatoes", slug: "potatoes" },
          { id: "1-2-3", name: "Beets", slug: "beets" },
        ],
      },
      {
        id: "1-3",
        name: "Cruciferous",
        slug: "cruciferous",
      },
    ],
  },
  {
    id: "2",
    name: "Fruits",
    slug: "fruits",
    image: "/fresh-colorful-fruits.jpg",
    subcategories: [
      {
        id: "2-1",
        name: "Berries",
        slug: "berries",
        subSubcategories: [
          { id: "2-1-1", name: "Strawberries", slug: "strawberries" },
          { id: "2-1-2", name: "Blueberries", slug: "blueberries" },
          { id: "2-1-3", name: "Raspberries", slug: "raspberries" },
        ],
      },
      {
        id: "2-2",
        name: "Citrus",
        slug: "citrus",
        subSubcategories: [
          { id: "2-2-1", name: "Oranges", slug: "oranges" },
          { id: "2-2-2", name: "Lemons", slug: "lemons" },
          { id: "2-2-3", name: "Limes", slug: "limes" },
        ],
      },
      {
        id: "2-3",
        name: "Tropical",
        slug: "tropical",
      },
    ],
  },
  {
    id: "3",
    name: "Dairy",
    slug: "dairy",
    image: "/assorted-dairy-products-milk-cheese.jpg",
    subcategories: [
      {
        id: "3-1",
        name: "Milk & Cream",
        slug: "milk-cream",
      },
      {
        id: "3-2",
        name: "Cheese",
        slug: "cheese",
      },
      {
        id: "3-3",
        name: "Yogurt",
        slug: "yogurt",
      },
    ],
  },
  {
    id: "4",
    name: "Meat & Seafood",
    slug: "meat-seafood",
    image: "/fresh-meat-seafood.jpg",
    subcategories: [
      {
        id: "4-1",
        name: "Beef",
        slug: "beef",
      },
      {
        id: "4-2",
        name: "Chicken",
        slug: "chicken",
      },
      {
        id: "4-3",
        name: "Seafood",
        slug: "seafood",
      },
    ],
  },
  {
    id: "5",
    name: "Bakery",
    slug: "bakery",
    image: "/fresh-bakery-bread-and-pastries.jpg",
    subcategories: [
      {
        id: "5-1",
        name: "Bread",
        slug: "bread",
      },
      {
        id: "5-2",
        name: "Pastries",
        slug: "pastries",
      },
      {
        id: "5-3",
        name: "Cakes",
        slug: "cakes",
      },
    ],
  },
]

export const products: Product[] = [
  // Vegetables
  {
    id: "p1",
    name: "Organic Spinach",
    description: "Fresh organic spinach, perfect for salads and cooking",
    price: 3.99,
    originalPrice: 5.99,
    image: "/fresh-organic-spinach-bunch.jpg",
    category: "vegetables",
    subcategory: "leafy-greens",
    subSubcategory: "spinach",
    rating: 4.8,
    reviews: 245,
    inStock: true,
    unit: "per bunch",
    tags: ["organic", "fresh", "healthy"],
  },
  {
    id: "p2",
    name: "Crispy Lettuce",
    description: "Crisp and fresh iceberg lettuce",
    price: 2.49,
    image: "/fresh-iceberg-lettuce-head.jpg",
    category: "vegetables",
    subcategory: "leafy-greens",
    subSubcategory: "lettuce",
    rating: 4.6,
    reviews: 189,
    inStock: true,
    unit: "per head",
    tags: ["fresh", "salad"],
  },
  {
    id: "p3",
    name: "Kale Bunch",
    description: "Nutrient-rich kale, great for smoothies",
    price: 4.99,
    image: "/fresh-kale-bunch.jpg",
    category: "vegetables",
    subcategory: "leafy-greens",
    subSubcategory: "kale",
    rating: 4.7,
    reviews: 156,
    inStock: true,
    unit: "per bunch",
    tags: ["organic", "healthy", "superfood"],
  },
  {
    id: "p4",
    name: "Rainbow Carrots",
    description: "Colorful carrots with natural sweetness",
    price: 2.99,
    originalPrice: 3.99,
    image: "/rainbow-colored-carrots.jpg",
    category: "vegetables",
    subcategory: "root-vegetables",
    subSubcategory: "carrots",
    rating: 4.9,
    reviews: 312,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "colorful", "sweet"],
  },
  {
    id: "p5",
    name: "Russet Potatoes",
    description: "Premium russet potatoes for all your cooking needs",
    price: 3.49,
    image: "/russet-potatoes.jpg",
    category: "vegetables",
    subcategory: "root-vegetables",
    subSubcategory: "potatoes",
    rating: 4.5,
    reviews: 278,
    inStock: true,
    unit: "5 lb bag",
    tags: ["fresh", "versatile"],
  },

  // Fruits
  {
    id: "p6",
    name: "Fresh Strawberries",
    description: "Sweet and juicy strawberries",
    price: 5.99,
    originalPrice: 7.99,
    image: "/fresh-red-strawberries.jpg",
    category: "fruits",
    subcategory: "berries",
    subSubcategory: "strawberries",
    rating: 4.9,
    reviews: 456,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "sweet", "berries"],
  },
  {
    id: "p7",
    name: "Blueberries",
    description: "Plump and delicious blueberries",
    price: 6.99,
    image: "/fresh-blueberries.png",
    category: "fruits",
    subcategory: "berries",
    subSubcategory: "blueberries",
    rating: 4.8,
    reviews: 389,
    inStock: true,
    unit: "per pint",
    tags: ["fresh", "antioxidants", "berries"],
  },
  {
    id: "p8",
    name: "Raspberries",
    description: "Delicate and flavorful raspberries",
    price: 5.49,
    image: "/fresh-raspberries.jpg",
    category: "fruits",
    subcategory: "berries",
    subSubcategory: "raspberries",
    rating: 4.7,
    reviews: 234,
    inStock: true,
    unit: "per pint",
    tags: ["fresh", "delicate", "berries"],
  },
  {
    id: "p9",
    name: "Navel Oranges",
    description: "Sweet and seedless navel oranges",
    price: 4.99,
    originalPrice: 6.99,
    image: "/fresh-navel-oranges.jpg",
    category: "fruits",
    subcategory: "citrus",
    subSubcategory: "oranges",
    rating: 4.6,
    reviews: 267,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "citrus", "sweet"],
  },
  {
    id: "p10",
    name: "Fresh Lemons",
    description: "Bright and zesty lemons",
    price: 3.99,
    image: "/fresh-lemons.png",
    category: "fruits",
    subcategory: "citrus",
    subSubcategory: "lemons",
    rating: 4.7,
    reviews: 198,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "citrus", "zesty"],
  },

  // Dairy
  {
    id: "p11",
    name: "Whole Milk",
    description: "Fresh whole milk, 2L",
    price: 4.49,
    image: "/vintage-milk-bottle.png",
    category: "dairy",
    subcategory: "milk-cream",
    rating: 4.8,
    reviews: 523,
    inStock: true,
    unit: "2L",
    tags: ["dairy", "milk", "fresh"],
  },
  {
    id: "p12",
    name: "Cheddar Cheese",
    description: "Aged cheddar cheese block",
    price: 7.99,
    image: "/cheddar-cheese-block.png",
    category: "dairy",
    subcategory: "cheese",
    rating: 4.9,
    reviews: 412,
    inStock: true,
    unit: "500g",
    tags: ["dairy", "cheese", "aged"],
  },
  {
    id: "p13",
    name: "Greek Yogurt",
    description: "Creamy Greek yogurt, plain",
    price: 5.99,
    image: "/greek-yogurt-container.png",
    category: "dairy",
    subcategory: "yogurt",
    rating: 4.7,
    reviews: 334,
    inStock: true,
    unit: "750g",
    tags: ["dairy", "yogurt", "protein"],
  },
  {
    id: "p14",
    name: "Heavy Cream",
    description: "Premium heavy cream for cooking",
    price: 3.99,
    image: "/heavy-cream-bottle.jpg",
    category: "dairy",
    subcategory: "milk-cream",
    rating: 4.6,
    reviews: 267,
    inStock: true,
    unit: "473ml",
    tags: ["dairy", "cream", "cooking"],
  },
  {
    id: "p15",
    name: "Mozzarella Cheese",
    description: "Fresh mozzarella balls",
    price: 6.49,
    image: "/fresh-mozzarella-balls.jpg",
    category: "dairy",
    subcategory: "cheese",
    rating: 4.8,
    reviews: 289,
    inStock: true,
    unit: "250g",
    tags: ["dairy", "cheese", "fresh"],
  },

  // Meat & Seafood
  {
    id: "p16",
    name: "Ground Beef",
    description: "Lean ground beef, 1kg",
    price: 12.99,
    originalPrice: 14.99,
    image: "/ground-beef-package.png",
    category: "meat-seafood",
    subcategory: "beef",
    rating: 4.7,
    reviews: 445,
    inStock: true,
    unit: "1kg",
    tags: ["meat", "beef", "lean"],
  },
  {
    id: "p17",
    name: "Chicken Breast",
    description: "Boneless, skinless chicken breast",
    price: 9.99,
    image: "/chicken-breast-package.png",
    category: "meat-seafood",
    subcategory: "chicken",
    rating: 4.8,
    reviews: 567,
    inStock: true,
    unit: "1kg",
    tags: ["meat", "chicken", "protein"],
  },
  {
    id: "p18",
    name: "Atlantic Salmon",
    description: "Fresh Atlantic salmon fillet",
    price: 15.99,
    image: "/fresh-salmon-fillet.jpg",
    category: "meat-seafood",
    subcategory: "seafood",
    rating: 4.9,
    reviews: 389,
    inStock: true,
    unit: "500g",
    tags: ["seafood", "fish", "omega3"],
  },
  {
    id: "p19",
    name: "Beef Steak",
    description: "Premium ribeye steak",
    price: 18.99,
    image: "/premium-ribeye-steak.png",
    category: "meat-seafood",
    subcategory: "beef",
    rating: 4.9,
    reviews: 312,
    inStock: true,
    unit: "500g",
    tags: ["meat", "beef", "premium"],
  },
  {
    id: "p20",
    name: "Shrimp",
    description: "Fresh large shrimp",
    price: 14.99,
    image: "/fresh-large-shrimp.jpg",
    category: "meat-seafood",
    subcategory: "seafood",
    rating: 4.8,
    reviews: 278,
    inStock: true,
    unit: "500g",
    tags: ["seafood", "shrimp", "fresh"],
  },

  // Bakery
  {
    id: "p21",
    name: "Whole Wheat Bread",
    description: "Fresh whole wheat bread loaf",
    price: 3.99,
    image: "/whole-wheat-bread-loaf.jpg",
    category: "bakery",
    subcategory: "bread",
    rating: 4.7,
    reviews: 234,
    inStock: true,
    unit: "per loaf",
    tags: ["bakery", "bread", "healthy"],
  },
  {
    id: "p22",
    name: "Croissants",
    description: "Buttery French croissants",
    price: 5.99,
    image: "/buttery-french-croissants.jpg",
    category: "bakery",
    subcategory: "pastries",
    rating: 4.9,
    reviews: 456,
    inStock: true,
    unit: "per pack",
    tags: ["bakery", "pastries", "french"],
  },
  {
    id: "p23",
    name: "Chocolate Cake",
    description: "Rich chocolate layer cake",
    price: 12.99,
    image: "/rich-chocolate-layer-cake.jpg",
    category: "bakery",
    subcategory: "cakes",
    rating: 4.8,
    reviews: 389,
    inStock: true,
    unit: "per cake",
    tags: ["bakery", "cake", "chocolate"],
  },
  {
    id: "p24",
    name: "Sourdough Bread",
    description: "Artisan sourdough bread",
    price: 4.99,
    image: "/artisan-sourdough.jpg",
    category: "bakery",
    subcategory: "bread",
    rating: 4.8,
    reviews: 312,
    inStock: true,
    unit: "per loaf",
    tags: ["bakery", "bread", "artisan"],
  },
  {
    id: "p25",
    name: "Blueberry Muffins",
    description: "Fresh blueberry muffins",
    price: 4.49,
    image: "/fresh-blueberry-muffins.jpg",
    category: "bakery",
    subcategory: "pastries",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    unit: "per pack",
    tags: ["bakery", "pastries", "blueberry"],
  },
]

export const flyers: Flyer[] = [
  {
    id: "f1",
    title: "Fresh Vegetables Sale",
    category: "vegetables",
    startDate: "2025-10-17",
    endDate: "2025-10-24",
    coverImage: "/vegetables-sale-flyer.jpg",
    products: [
      { productId: "p1", discount: 33, flyerPrice: 3.99, position: 1 },
      { productId: "p4", discount: 25, flyerPrice: 2.99, position: 2 },
    ],
    isActive: true,
  },
  {
    id: "f2",
    title: "Berry Bonanza",
    category: "fruits",
    startDate: "2025-10-17",
    endDate: "2025-10-24",
    coverImage: "/berries-sale-flyer.jpg",
    products: [
      { productId: "p6", discount: 25, flyerPrice: 5.99, position: 1 },
      { productId: "p7", discount: 15, flyerPrice: 6.99, position: 2 },
    ],
    isActive: true,
  },
  {
    id: "f3",
    title: "Dairy Deals",
    category: "dairy",
    startDate: "2025-10-17",
    endDate: "2025-10-31",
    coverImage: "/dairy-products-sale.jpg",
    products: [
      { productId: "p11", discount: 10, flyerPrice: 4.49, position: 1 },
      { productId: "p12", discount: 15, flyerPrice: 7.99, position: 2 },
    ],
    isActive: true,
  },
]
