import type { Category, Flyer, Product } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Fruits",
    slug: "fruits",
    image: "/hero-fruits.jpg",
    subcategories: [
      {
        id: "1-1",
        name: "Apples",
        slug: "apples",
        image: "/assets/subcategories/apples.jpg",
        subSubcategories: [
          { id: "1-1-1", name: "Golden Apple", slug: "golden-apple" },
          { id: "1-1-2", name: "Pink Lady Apple", slug: "pink-lady-apple" },
          { id: "1-1-3", name: "Red Delicious Apple", slug: "red-delicious-apple" },
          { id: "1-1-4", name: "Granny Smith Apple", slug: "granny-smith-apple" },
          { id: "1-1-5", name: "Fuji Apple", slug: "fuji-apple" },
        ],
      },
      {
        id: "1-2",
        name: "Berries",
        slug: "berries",
        image: "/assets/subcategories/berries.jpg",
        subSubcategories: [
          { id: "1-2-1", name: "Strawberries", slug: "strawberries" },
          { id: "1-2-2", name: "Blueberries", slug: "blueberries" },
          { id: "1-2-3", name: "Blackberries", slug: "blackberries" },
          { id: "1-2-4", name: "Raspberry", slug: "raspberry" },
          { id: "1-2-5", name: "Golden Berries", slug: "golden-berries" },
        ],
      },
      {
        id: "1-3",
        name: "Citrus",
        slug: "citrus",
        image: "/assets/subcategories/citrus.jpg",
        subSubcategories: [
          { id: "1-3-1", name: "Clementine", slug: "clementine" },
          { id: "1-3-2", name: "Navel Orange", slug: "navel-orange" },
          { id: "1-3-3", name: "Grapefruit", slug: "grapefruit" },
          { id: "1-3-4", name: "Lemon", slug: "lemon" },
          { id: "1-3-5", name: "Lime", slug: "lime" },
        ],
      },
      {
        id: "1-4",
        name: "Grapes",
        slug: "grapes",
        image: "/assets/subcategories/grapes.jpg",
        subSubcategories: [
          { id: "1-4-1", name: "Red Grapes", slug: "red-grapes" },
          { id: "1-4-2", name: "Green Grapes", slug: "green-grapes" },
        ],
      },
      {
        id: "1-5",
        name: "Melons",
        slug: "melons",
        image: "/assets/subcategories/melons.jpg",
        subSubcategories: [
          { id: "1-5-1", name: "Watermelon", slug: "watermelon" },
          { id: "1-5-2", name: "Cantaloupe", slug: "cantaloupe" },
          { id: "1-5-3", name: "Melon Hami", slug: "melon-hami" },
          { id: "1-5-4", name: "Canary Melon", slug: "canary-melon" },
          { id: "1-5-5", name: "Honeydew", slug: "honeydew" },
          { id: "1-5-6", name: "Honeydew Golden", slug: "honeydew-golden" },
          { id: "1-5-7", name: "Red Falcon Melon", slug: "red-falcon-melon" },
        ],
      },
      {
        id: "1-6",
        name: "Pears",
        slug: "pears",
        image: "/assets/subcategories/pears.jpg",
        subSubcategories: [
          { id: "1-6-1", name: "Bartlett Pear", slug: "bartlett-pear" },
          { id: "1-6-2", name: "Bosc Pear", slug: "bosc-pear" },
        ],
      },
      {
        id: "1-7",
        name: "Tropicals",
        slug: "tropicals",
        image: "/assets/subcategories/tropicals.jpg",
        subSubcategories: [
          { id: "1-7-1", name: "Pineapple", slug: "pineapple" },
          { id: "1-7-2", name: "Ataulfo Mango", slug: "ataulfo-mango" },
          { id: "1-7-3", name: "Baby Mango", slug: "baby-mango" },
          { id: "1-7-4", name: "Passion Fruit", slug: "passion-fruit" },
          { id: "1-7-5", name: "Granadilla", slug: "granadilla" },
        ],
      },
      {
        id: "1-8",
        name: "Stone Fruits",
        slug: "stone-fruits",
        image: "/assets/subcategories/stone-fruits.jpg",
        subSubcategories: [
          { id: "1-8-1", name: "Nectarine", slug: "nectarine" },
          { id: "1-8-2", name: "Peach", slug: "peach" },
          { id: "1-8-3", name: "Cherries", slug: "cherries" },
          { id: "1-8-4", name: "White Cherries", slug: "white-cherries" },
        ],
      },
      {
        id: "1-9",
        name: "Dates",
        slug: "dates",
      },
      {
        id: "1-10",
        name: "Others",
        slug: "others",
        image: "/assets/subcategories/others-fruits.jpg",
        subSubcategories: [
          { id: "1-10-1", name: "Avocado", slug: "avocado" },
          { id: "1-10-2", name: "Dragon Fruit", slug: "dragon-fruit" },
          { id: "1-10-3", name: "Black Fig", slug: "black-fig" },
          { id: "1-10-4", name: "Kiwi", slug: "kiwi" },
          { id: "1-10-5", name: "Pomegranate", slug: "pomegranate" },
          { id: "1-10-6", name: "Cactus Pear", slug: "cactus-pear" },
          { id: "1-10-7", name: "Quince", slug: "quince" },
          { id: "1-10-8", name: "Persimmon", slug: "persimmon" },
          { id: "1-10-9", name: "Loquat", slug: "loquat" },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Vegetables",
    slug: "vegetables",
    image: "/vegetables-hero.jpg",
    subcategories: [
      {
        id: "2-1",
        name: "Dry Vegetables",
        slug: "dry-vegetables",
        subSubcategories: [
          {
            id: "2-1-1",
            name: "Potatoes",
            slug: "potatoes",
            image: "/assets/subcategories/potatoes.jpg",
          },
          {
            id: "2-1-2",
            name: "Onions",
            slug: "onions",
            image: "/assets/subcategories/onions.jpg",
          },
          {
            id: "2-1-3",
            name: "Others",
            slug: "others-dry",
            image: "/assets/subcategories/dry-vegetables-others.jpg",
          },
        ],
      },
      {
        id: "2-2",
        name: "Tomatoes",
        slug: "tomatoes",
        image: "/assets/subcategories/tomatoes.jpg",
        subSubcategories: [
          { id: "2-2-1", name: "Roma Tomatoes", slug: "roma-tomatoes" },
          { id: "2-2-2", name: "Grape Tomatoes", slug: "grape-tomatoes" },
          { id: "2-2-3", name: "Beefsteak Tomatoes", slug: "beefsteak-tomatoes" },
          { id: "2-2-4", name: "Tomato Cherry On The Vine", slug: "cherry-vine-tomatoes" },
          { id: "2-2-5", name: "Mixed Medley Tomatoes", slug: "mixed-medley-tomatoes" },
          { id: "2-2-6", name: "Heirloom Tomatoes", slug: "heirloom-tomatoes" },
        ],
      },
      {
        id: "2-3",
        name: "Peppers",
        slug: "peppers",
        image: "/assets/subcategories/peppers.jpg",
        subSubcategories: [
          { id: "2-3-1", name: "Green Bell Pepper", slug: "green-bell-pepper" },
          { id: "2-3-2", name: "Yellow Bell Pepper", slug: "yellow-bell-pepper" },
          { id: "2-3-3", name: "Red Bell Pepper", slug: "red-bell-pepper" },
          { id: "2-3-4", name: "Orange Bell Pepper", slug: "orange-bell-pepper" },
          { id: "2-3-5", name: "Shepherd Pepper", slug: "shepherd-pepper" },
          { id: "2-3-6", name: "Shishito Pepper", slug: "shishito-pepper" },
          { id: "2-3-7", name: "Red Rustico Pepper", slug: "red-rustico-pepper" },
        ],
      },
      {
        id: "2-4",
        name: "Wet Vegetables",
        slug: "wet-vegetables",
        image: "/assets/subcategories/wet-vegetables.jpg",
        subSubcategories: [
          { id: "2-4-1", name: "Broccoli crown", slug: "broccoli-crown" },
          { id: "2-4-2", name: "Spinach", slug: "spinach" },
          { id: "2-4-3", name: "Celery", slug: "celery" },
          { id: "2-4-4", name: "Romaine Lettuce", slug: "romaine-lettuce" },
          { id: "2-4-5", name: "Asparagus", slug: "asparagus" },
          { id: "2-4-6", name: "Onion Green", slug: "green-onion" },
          { id: "2-4-7", name: "Bi-Colour Corn", slug: "bicolour-corn" },
          { id: "2-4-8", name: "Radish", slug: "radish" },
          { id: "2-4-9", name: "Anise / Fennel", slug: "fennel" },
          { id: "2-4-10", name: "Sprout Brussels", slug: "brussels-sprouts" },
          { id: "2-4-11", name: "French Beans", slug: "french-beans" },
          { id: "2-4-12", name: "Endive Lettuce", slug: "endive-lettuce" },
          { id: "2-4-13", name: "Leeks", slug: "leeks" },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Organic Fruits",
    slug: "organic-fruits",
    image: "/organic-fruits-hero.jpg",
    subcategories: [
      {
        id: "3-1",
        name: "Apples",
        slug: "organic-apples",
        image: "/assets/subcategories/apples.jpg",
        subSubcategories: [
          { id: "3-1-1", name: "Golden Apple", slug: "organic-golden-apple" },
          { id: "3-1-2", name: "Pink Lady Apple", slug: "organic-pink-lady-apple" },
          { id: "3-1-3", name: "Red Delicious Apple", slug: "organic-red-delicious-apple" },
          { id: "3-1-4", name: "Granny Smith Apple", slug: "organic-granny-smith-apple" },
          { id: "3-1-5", name: "Fuji Apple", slug: "organic-fuji-apple" },
        ],
      },
      {
        id: "3-2",
        name: "Berries",
        slug: "organic-berries",
        image: "/assets/subcategories/berries.jpg",
        subSubcategories: [
          { id: "3-2-1", name: "Strawberries", slug: "organic-strawberries" },
          { id: "3-2-2", name: "Blueberries", slug: "organic-blueberries" },
          { id: "3-2-3", name: "Blackberries", slug: "organic-blackberries" },
          { id: "3-2-4", name: "Raspberry", slug: "organic-raspberry" },
        ],
      },
      {
        id: "3-3",
        name: "Citrus",
        slug: "organic-citrus",
        image: "/assets/subcategories/citrus.jpg",
        subSubcategories: [
          { id: "3-3-1", name: "Clementine", slug: "organic-clementine" },
          { id: "3-3-2", name: "Navel Orange", slug: "organic-navel-orange" },
          { id: "3-3-3", name: "Grapefruit", slug: "organic-grapefruit" },
          { id: "3-3-4", name: "Lemon", slug: "organic-lemon" },
        ],
      },
      {
        id: "3-4",
        name: "Grapes",
        slug: "organic-grapes",
        image: "/assets/subcategories/grapes.jpg",
        subSubcategories: [
          { id: "3-4-1", name: "Red Grapes", slug: "organic-red-grapes" },
          { id: "3-4-2", name: "Green Grapes", slug: "organic-green-grapes" },
        ],
      },
      {
        id: "3-5",
        name: "Melons",
        slug: "organic-melons",
        image: "/assets/subcategories/melons.jpg",
        subSubcategories: [
          { id: "3-5-1", name: "Watermelon", slug: "organic-watermelon" },
          { id: "3-5-2", name: "Cantaloupe", slug: "organic-cantaloupe" },
          { id: "3-5-3", name: "Canary Melon", slug: "organic-canary-melon" },
        ],
      },
      {
        id: "3-6",
        name: "Pears",
        slug: "organic-pears",
        image: "/assets/subcategories/pears.jpg",
        subSubcategories: [
          { id: "3-6-1", name: "Bartlett Pear", slug: "organic-bartlett-pear" },
          { id: "3-6-2", name: "Bosc Pear", slug: "organic-bosc-pear" },
        ],
      },
      {
        id: "3-7",
        name: "Tropicals",
        slug: "organic-tropicals",
        image: "/assets/subcategories/tropicals.jpg",
        subSubcategories: [
          { id: "3-7-1", name: "Pineapple", slug: "organic-pineapple" },
          { id: "3-7-2", name: "Ataulfo Mango", slug: "organic-ataulfo-mango" },
        ],
      },
      {
        id: "3-8",
        name: "Others",
        slug: "organic-others",
        image: "/assets/subcategories/others-fruits.jpg",
        subSubcategories: [
          { id: "3-8-1", name: "Nectarine", slug: "organic-nectarine" },
          { id: "3-8-2", name: "Cherries", slug: "organic-cherries" },
          { id: "3-8-3", name: "Cactus Pear", slug: "organic-cactus-pear" },
          { id: "3-8-4", name: "Avocado", slug: "organic-avocado" },
          { id: "3-8-5", name: "Kiwi", slug: "organic-kiwi" },
        ],
      },
    ],
  },
  {
    id: "4",
    name: "Organic Vegetables",
    slug: "organic-vegetables",
    image: "/organic-vegetables-hero.jpg",
    subcategories: [
      {
        id: "4-1",
        name: "Dry Vegetables",
        slug: "organic-dry-vegetables",
        subSubcategories: [
          {
            id: "4-1-1",
            name: "Potatoes",
            slug: "organic-potatoes",
            image: "/assets/subcategories/potatoes.jpg",
          },
          {
            id: "4-1-2",
            name: "Onions",
            slug: "organic-onions",
            image: "/assets/subcategories/onions.jpg",
          },
          {
            id: "4-1-3",
            name: "Others",
            slug: "organic-others-dry",
            image: "/assets/subcategories/dry-vegetables-others.jpg",
          },
        ],
      },
      {
        id: "4-2",
        name: "Tomatoes",
        slug: "organic-tomatoes",
        image: "/assets/subcategories/tomatoes.jpg",
        subSubcategories: [
          { id: "4-2-1", name: "Grape Tomatoes", slug: "organic-grape-tomatoes" },
          { id: "4-2-2", name: "Beefsteak Tomatoes", slug: "organic-beefsteak-tomatoes" },
          { id: "4-2-3", name: "Tomato Cherry On The Vine", slug: "organic-cherry-vine-tomatoes" },
        ],
      },
      {
        id: "4-3",
        name: "Peppers",
        slug: "organic-peppers",
        image: "/assets/subcategories/peppers.jpg",
        subSubcategories: [
          { id: "4-3-1", name: "Green Bell Pepper", slug: "organic-green-bell-pepper" },
          { id: "4-3-2", name: "Yellow Bell Pepper", slug: "organic-yellow-bell-pepper" },
          { id: "4-3-3", name: "Red Bell Pepper", slug: "organic-red-bell-pepper" },
          { id: "4-3-4", name: "Red Rustico Pepper", slug: "organic-red-rustico-pepper" },
        ],
      },
      {
        id: "4-4",
        name: "Wet Vegetables",
        slug: "organic-wet-vegetables",
        image: "/assets/subcategories/wet-vegetables.jpg",
        subSubcategories: [
          { id: "4-4-1", name: "Broccoli crown", slug: "organic-broccoli-crown" },
          { id: "4-4-2", name: "Spinach", slug: "organic-spinach" },
          { id: "4-4-3", name: "Celery", slug: "organic-celery" },
          { id: "4-4-4", name: "Onion Green", slug: "organic-green-onion" },
        ],
      },
    ],
  },
];

export const products: Product[] = [
  // Fruits - Apples
  {
    id: "f-apple-1",
    name: "Golden Apple",
    description: "Sweet and crisp Golden Apple with a delicate flavor",
    price: 3.99,
    image: "/assets/products/golden-apple.jpg",
    category: "fruits",
    subcategory: "apples",
    subSubcategory: "golden-apple",
    rating: 4.8,
    reviews: 245,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "sweet", "apples"],
  },
  {
    id: "f-apple-2",
    name: "Pink Lady Apple",
    description: "Crisp and tangy-sweet Pink Lady Apple",
    price: 4.49,
    image: "/assets/products/pink-lady-apple.jpg",
    category: "fruits",
    subcategory: "apples",
    subSubcategory: "pink-lady-apple",
    rating: 4.9,
    reviews: 312,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "crisp", "apples"],
  },
  {
    id: "f-apple-3",
    name: "Red Delicious Apple",
    description: "Classic Red Delicious Apple, mildly sweet",
    price: 3.49,
    image: "/assets/products/red-delicious-apple.jpg",
    category: "fruits",
    subcategory: "apples",
    subSubcategory: "red-delicious-apple",
    rating: 4.5,
    reviews: 198,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "classic", "apples"],
  },
  {
    id: "f-apple-4",
    name: "Granny Smith Apple",
    description: "Tart and crisp Granny Smith Apple, perfect for baking",
    price: 3.29,
    image: "/assets/products/granny-smith-apple.jpg",
    category: "fruits",
    subcategory: "apples",
    subSubcategory: "granny-smith-apple",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "tart", "apples", "baking"],
  },
  {
    id: "f-apple-5",
    name: "Fuji Apple",
    description: "Sweet and juicy Fuji Apple with crisp texture",
    price: 4.29,
    image: "/assets/products/fuji-apple.jpg",
    category: "fruits",
    subcategory: "apples",
    subSubcategory: "fuji-apple",
    rating: 4.9,
    reviews: 389,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "sweet", "juicy", "apples"],
  },

  // Fruits - Berries
  {
    id: "f-berry-1",
    name: "Fresh Strawberries",
    description: "Sweet and juicy strawberries, perfect for snacking",
    price: 5.99,
    originalPrice: 7.99,
    image: "/assets/products/strawberries.jpg",
    category: "fruits",
    subcategory: "berries",
    subSubcategory: "strawberries",
    rating: 4.9,
    reviews: 456,
    inStock: true,
    unit: "per pint",
    tags: ["fresh", "sweet", "berries"],
  },
  {
    id: "f-berry-2",
    name: "Blueberries",
    description: "Plump and delicious blueberries, packed with antioxidants",
    price: 6.99,
    image: "/assets/subcategories/berries.jpg",
    category: "fruits",
    subcategory: "berries",
    subSubcategory: "blueberries",
    rating: 4.8,
    reviews: 389,
    inStock: true,
    unit: "per pint",
    tags: ["fresh", "antioxidants", "berries"],
  },
  {
    id: "f-berry-3",
    name: "Blackberries",
    description: "Fresh blackberries with rich flavor",
    price: 5.49,
    image: "/assets/subcategories/berries.jpg",
    category: "fruits",
    subcategory: "berries",
    subSubcategory: "blackberries",
    rating: 4.7,
    reviews: 234,
    inStock: true,
    unit: "per pint",
    tags: ["fresh", "berries"],
  },
  {
    id: "f-berry-4",
    name: "Raspberries",
    description: "Delicate and flavorful raspberries",
    price: 5.99,
    image: "/assets/subcategories/berries.jpg",
    category: "fruits",
    subcategory: "berries",
    subSubcategory: "raspberry",
    rating: 4.8,
    reviews: 278,
    inStock: true,
    unit: "per pint",
    tags: ["fresh", "delicate", "berries"],
  },
  {
    id: "f-berry-5",
    name: "Golden Berries",
    description: "Exotic golden berries with tangy-sweet flavor",
    price: 7.99,
    image: "/assets/subcategories/berries.jpg",
    category: "fruits",
    subcategory: "berries",
    subSubcategory: "golden-berries",
    rating: 4.6,
    reviews: 156,
    inStock: true,
    unit: "per pint",
    tags: ["fresh", "exotic", "berries"],
  },

  // Fruits - Citrus
  {
    id: "f-citrus-1",
    name: "Clementines",
    description: "Sweet and easy-to-peel clementines",
    price: 4.99,
    image: "/assets/subcategories/citrus.jpg",
    category: "fruits",
    subcategory: "citrus",
    subSubcategory: "clementine",
    rating: 4.8,
    reviews: 312,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "sweet", "citrus"],
  },
  {
    id: "f-citrus-2",
    name: "Navel Oranges",
    description: "Seedless navel oranges, perfect for juicing",
    price: 3.99,
    image: "/assets/subcategories/citrus.jpg",
    category: "fruits",
    subcategory: "citrus",
    subSubcategory: "navel-orange",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "seedless", "citrus", "juicing"],
  },
  {
    id: "f-citrus-3",
    name: "Grapefruits",
    description: "Tangy pink grapefruits, rich in vitamin C",
    price: 4.49,
    image: "/assets/subcategories/citrus.jpg",
    category: "fruits",
    subcategory: "citrus",
    subSubcategory: "grapefruit",
    rating: 4.5,
    reviews: 198,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "tangy", "citrus", "vitamin-c"],
  },
  {
    id: "f-citrus-4",
    name: "Lemons",
    description: "Bright and zesty lemons for cooking and drinks",
    price: 3.99,
    image: "/assets/subcategories/citrus.jpg",
    category: "fruits",
    subcategory: "citrus",
    subSubcategory: "lemon",
    rating: 4.8,
    reviews: 345,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "zesty", "citrus", "cooking"],
  },
  {
    id: "f-citrus-5",
    name: "Limes",
    description: "Fresh limes with bright, acidic flavor",
    price: 4.29,
    image: "/assets/subcategories/citrus.jpg",
    category: "fruits",
    subcategory: "citrus",
    subSubcategory: "lime",
    rating: 4.7,
    reviews: 234,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "citrus", "acidic"],
  },

  // Vegetables - Dry Vegetables - Potatoes
  {
    id: "v-potato-1",
    name: "Yellow Potatoes",
    description: "Buttery yellow potatoes, perfect for roasting",
    price: 2.99,
    image: "/assets/subcategories/potatoes.jpg",
    category: "vegetables",
    subcategory: "dry-vegetables",
    subSubcategory: "potatoes",
    rating: 4.7,
    reviews: 289,
    inStock: true,
    unit: "5 lb bag",
    tags: ["fresh", "versatile", "potatoes"],
  },
  {
    id: "v-potato-2",
    name: "Red Potatoes",
    description: "Waxy red potatoes, great for salads",
    price: 3.29,
    image: "/assets/subcategories/potatoes.jpg",
    category: "vegetables",
    subcategory: "dry-vegetables",
    subSubcategory: "potatoes",
    rating: 4.6,
    reviews: 245,
    inStock: true,
    unit: "5 lb bag",
    tags: ["fresh", "waxy", "potatoes", "salads"],
  },
  {
    id: "v-potato-3",
    name: "Russet Potatoes",
    description: "Classic russet potatoes for baking and frying",
    price: 2.79,
    image: "/assets/subcategories/potatoes.jpg",
    category: "vegetables",
    subcategory: "dry-vegetables",
    subSubcategory: "potatoes",
    rating: 4.8,
    reviews: 412,
    inStock: true,
    unit: "10 lb bag",
    tags: ["fresh", "baking", "potatoes"],
  },
  {
    id: "v-potato-4",
    name: "Yukon Mini Potatoes",
    description: "Baby Yukon potatoes, perfect for roasting whole",
    price: 4.99,
    image: "/assets/subcategories/potatoes.jpg",
    category: "vegetables",
    subcategory: "dry-vegetables",
    subSubcategory: "potatoes",
    rating: 4.9,
    reviews: 334,
    inStock: true,
    unit: "3 lb bag",
    tags: ["fresh", "baby", "potatoes", "roasting"],
  },

  // Vegetables - Dry Vegetables - Onions
  {
    id: "v-onion-1",
    name: "Yellow Onions",
    description: "Versatile yellow onions for everyday cooking",
    price: 1.99,
    image: "/assets/subcategories/onions.jpg",
    category: "vegetables",
    subcategory: "dry-vegetables",
    subSubcategory: "onions",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    unit: "3 lb bag",
    tags: ["fresh", "versatile", "onions"],
  },
  {
    id: "v-onion-2",
    name: "Red Onions",
    description: "Mild and sweet red onions, great for salads",
    price: 2.49,
    image: "/assets/subcategories/onions.jpg",
    category: "vegetables",
    subcategory: "dry-vegetables",
    subSubcategory: "onions",
    rating: 4.8,
    reviews: 298,
    inStock: true,
    unit: "3 lb bag",
    tags: ["fresh", "sweet", "onions", "salads"],
  },

  // Vegetables - Tomatoes
  {
    id: "v-tomato-1",
    name: "Roma Tomatoes",
    description: "Meaty Roma tomatoes, perfect for sauces",
    price: 3.49,
    image: "/assets/subcategories/tomatoes.jpg",
    category: "vegetables",
    subcategory: "tomatoes",
    subSubcategory: "roma-tomatoes",
    rating: 4.7,
    reviews: 234,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "meaty", "tomatoes", "sauce"],
  },
  {
    id: "v-tomato-2",
    name: "Grape Tomatoes",
    description: "Sweet grape tomatoes, ideal for snacking",
    price: 4.99,
    image: "/assets/subcategories/tomatoes.jpg",
    category: "vegetables",
    subcategory: "tomatoes",
    subSubcategory: "grape-tomatoes",
    rating: 4.9,
    reviews: 389,
    inStock: true,
    unit: "per pint",
    tags: ["fresh", "sweet", "tomatoes", "snacking"],
  },
  {
    id: "v-tomato-3",
    name: "Beefsteak Tomatoes",
    description: "Large beefsteak tomatoes, perfect for sandwiches",
    price: 4.49,
    image: "/assets/subcategories/tomatoes.jpg",
    category: "vegetables",
    subcategory: "tomatoes",
    subSubcategory: "beefsteak-tomatoes",
    rating: 4.8,
    reviews: 312,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "large", "tomatoes", "sandwiches"],
  },
  {
    id: "v-tomato-4",
    name: "Cherry Tomatoes on Vine",
    description: "Sweet cherry tomatoes on the vine",
    price: 5.49,
    image: "/assets/subcategories/tomatoes.jpg",
    category: "vegetables",
    subcategory: "tomatoes",
    subSubcategory: "cherry-vine-tomatoes",
    rating: 4.9,
    reviews: 423,
    inStock: true,
    unit: "per package",
    tags: ["fresh", "sweet", "tomatoes", "vine"],
  },
  {
    id: "v-tomato-5",
    name: "Mixed Medley Tomatoes",
    description: "Colorful mix of heirloom tomatoes",
    price: 6.99,
    image: "/assets/subcategories/tomatoes.jpg",
    category: "vegetables",
    subcategory: "tomatoes",
    subSubcategory: "mixed-medley-tomatoes",
    rating: 4.8,
    reviews: 267,
    inStock: true,
    unit: "per package",
    tags: ["fresh", "colorful", "tomatoes", "heirloom"],
  },
  {
    id: "v-tomato-6",
    name: "Heirloom Tomatoes",
    description: "Traditional heirloom tomatoes with rich flavor",
    price: 5.99,
    image: "/assets/subcategories/tomatoes.jpg",
    category: "vegetables",
    subcategory: "tomatoes",
    subSubcategory: "heirloom-tomatoes",
    rating: 4.9,
    reviews: 345,
    inStock: true,
    unit: "per lb",
    tags: ["fresh", "heirloom", "tomatoes", "flavorful"],
  },

  // Vegetables - Peppers
  {
    id: "v-pepper-1",
    name: "Green Bell Pepper",
    description: "Crisp green bell peppers for cooking",
    price: 1.99,
    image: "/assets/subcategories/peppers.jpg",
    category: "vegetables",
    subcategory: "peppers",
    subSubcategory: "green-bell-pepper",
    rating: 4.6,
    reviews: 198,
    inStock: true,
    unit: "each",
    tags: ["fresh", "crisp", "peppers"],
  },
  {
    id: "v-pepper-2",
    name: "Yellow Bell Pepper",
    description: "Sweet yellow bell peppers",
    price: 2.49,
    image: "/assets/subcategories/peppers.jpg",
    category: "vegetables",
    subcategory: "peppers",
    subSubcategory: "yellow-bell-pepper",
    rating: 4.7,
    reviews: 234,
    inStock: true,
    unit: "each",
    tags: ["fresh", "sweet", "peppers"],
  },
  {
    id: "v-pepper-3",
    name: "Red Bell Pepper",
    description: "Sweet and vibrant red bell peppers",
    price: 2.49,
    image: "/assets/subcategories/peppers.jpg",
    category: "vegetables",
    subcategory: "peppers",
    subSubcategory: "red-bell-pepper",
    rating: 4.8,
    reviews: 289,
    inStock: true,
    unit: "each",
    tags: ["fresh", "sweet", "peppers"],
  },
  {
    id: "v-pepper-4",
    name: "Orange Bell Pepper",
    description: "Sweet orange bell peppers",
    price: 2.49,
    image: "/assets/subcategories/peppers.jpg",
    category: "vegetables",
    subcategory: "peppers",
    subSubcategory: "orange-bell-pepper",
    rating: 4.7,
    reviews: 212,
    inStock: true,
    unit: "each",
    tags: ["fresh", "sweet", "peppers"],
  },

  // Organic Fruits - Apples
  {
    id: "of-apple-1",
    name: "Organic Golden Apple",
    description: "Certified organic Golden Apple",
    price: 4.99,
    image: "/assets/products/golden-apple.jpg",
    category: "organic-fruits",
    subcategory: "organic-apples",
    subSubcategory: "organic-golden-apple",
    rating: 4.9,
    reviews: 178,
    inStock: true,
    unit: "per lb",
    tags: ["organic", "fresh", "sweet", "apples"],
  },
  {
    id: "of-apple-2",
    name: "Organic Pink Lady Apple",
    description: "Certified organic Pink Lady Apple",
    price: 5.49,
    image: "/assets/products/pink-lady-apple.jpg",
    category: "organic-fruits",
    subcategory: "organic-apples",
    subSubcategory: "organic-pink-lady-apple",
    rating: 4.9,
    reviews: 223,
    inStock: true,
    unit: "per lb",
    tags: ["organic", "fresh", "crisp", "apples"],
  },

  // Organic Vegetables - Potatoes
  {
    id: "ov-potato-1",
    name: "Organic Yellow Potatoes",
    description: "Certified organic yellow potatoes",
    price: 3.99,
    image: "/assets/subcategories/potatoes.jpg",
    category: "organic-vegetables",
    subcategory: "organic-dry-vegetables",
    subSubcategory: "organic-potatoes",
    rating: 4.8,
    reviews: 198,
    inStock: true,
    unit: "5 lb bag",
    tags: ["organic", "fresh", "potatoes"],
  },
  {
    id: "ov-potato-2",
    name: "Organic Russet Potatoes",
    description: "Certified organic russet potatoes",
    price: 3.79,
    image: "/assets/subcategories/potatoes.jpg",
    category: "organic-vegetables",
    subcategory: "organic-dry-vegetables",
    subSubcategory: "organic-potatoes",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    unit: "10 lb bag",
    tags: ["organic", "fresh", "baking", "potatoes"],
  },
];


export const flyers: Flyer[] = [
  {
    id: "f1",
    title: "Fresh Vegetables Sale",
    category: "vegetables",
    startDate: "2025-10-17",
    endDate: "2025-10-24",
    coverImage: "/vegetables-sale-flyer.jpg",
    products: [
      { productId: "v-potato-1", discount: 33, flyerPrice: 3.99, position: 1 },
      { productId: "v-potato-4", discount: 25, flyerPrice: 2.99, position: 2 },
    ],
    isActive: true,
  },
  {
    id: "f2",
    title: "Berry Bonanza",
    category: "fruits",
    startDate: "2025-10-17",
    endDate: "2025-10-24",
    coverImage: "/berries-sale-flyer.jpg",
    products: [
      { productId: "f-berry-5", discount: 25, flyerPrice: 5.99, position: 1 },
      { productId: "f-berry-2", discount: 15, flyerPrice: 6.99, position: 2 },
    ],
    isActive: true,
  },
  {
    id: "f3",
    title: "Organic fruit Special",
    category: "organic-fruits",
    startDate: "2025-10-17",
    endDate: "2025-10-31",
    coverImage: "/dairy-products-sale.jpg",
    products: [
      { productId: "f-apple-4", discount: 10, flyerPrice: 4.49, position: 1 },
      { productId: "f-citrus-3", discount: 15, flyerPrice: 7.99, position: 2 },
    ],
    isActive: true,
  },
  {
    id: "f4",
    title: "Organic fruit Special",
    category: "organic-vegetables",
    startDate: "2025-10-17",
    endDate: "2025-10-31",
    coverImage: "/Organic-vegetable-cover-flyer.png",
    products: [
      { productId: "f-apple-4", discount: 10, flyerPrice: 4.49, position: 1 },
      { productId: "f-citrus-3", discount: 15, flyerPrice: 7.99, position: 2 },
    ],
    isActive: true,
  },
]